package ua.nure.storozhuk.SummaryTask4;

import java.util.ListResourceBundle;

public class Words_ru extends ListResourceBundle{
	public Object[][] getContents() {
	      return contents;
	   }
	   static final Object[][] contents = {   
		  {"en.Teacher", "Преподаватель"},
		  {"en.Student", "Студент"},
		  {"en.Admin", "Администратор"},
		  {"en.teacher", "преподаватель"},
		  {"en.student", "студент"},
		  {"en.admin", "администратор"},
		  {"en.studentBlocked", "студент заблокирован"},
	      {"en.Course", "Курс"},
	      {"en.Mark", "Оценка"},
	      {"en.Log In", "Войти"},
	      {"en.Logout", "Выйти"},
	      {"en.Login", "Логин"},
	      {"en.Status", "Статус"},
	      {"en.My courses", "Мои курсы"},
	      {"en.Welcome", "Добро пожаловать"},
	      {"en.Password", "Пароль"},
	      {"en.Sign Up", "Зарегистрироваться"},
	      {"en.Table of courses done by student", "Курсы, которые окончил студент"},
	      {"en.Courses in preparing", "Не начатые курсы"},
	      {"en.Finished courses", "Оконченные курсы"},
	      {"en.Courses in progress", "Начавшиеся курсы"},
	      {"en.Other courses", "Прочие курсы"},
	      {"en.If you don't have an account", "Если у вас нету аккаунта"},
	      {"en. Your request for a teacher position is in processing", "Ваша регистрация на роль преподавателя находится на рассмотрении"
	      		+ " у администраторов"},
	      {"en.Courses list", "Список курсов"},
	      {"en.Users list", "Список пользователей"},
	      {"en.Teachers requests", "Регистрация преподавателей"},
	      {"en.Status to register", "С каким статусом регистрировать?"},
	      {"en.Insert new course", "Добавить курс"},
	      {"en.Subject", "Предмет"},
	      {"en.Start date", "Дата начала"},
	      {"en.Start date YYYY-MM-DD", "Дата начала ГГГГ-ММ-ДД"},
	      {"en.End date", "Дата окончания"},
	      {"en.End date YYYY-MM-DD", "Дата окончания ГГГГ-ММ-ДД"},
	      {"en.Teacher ID", "ID преподавателя"},
	      {"en.Create", "Создать"},
	      {"en.Update", "Обновить"},
	      {"en.Delete", "Удалить"},
	      {"en.Course ID", "ID курса"},
	      {"en.Update course with ID", "Обновление курса с ID"},
	      {"en.Apply", "Принять"},
	      {"en.Block", "Заблокировать"},
	      {"en.Unblock", "Разблокировать"},
	      {"en.User information", "Информация о пользователе"},
	      {"en.Sort courses by students count", "Сортировка по количеству студентов"},
	      {"en.All teachers", "Все преподаватели"},
	      {"en.All subjects", "Все предметы"},
	      {"en.You are blocked", "Вы заблокированы"},
	      {"en.Table of courses which are not started", "Таблица курсов, которые не начаты"},
	      {"en.Table of courses which are in progress", "Таблица начатых курсов"},
	      {"en.Rating sort", "Сортировка по кол-ву студентов"},
	      {"en.Table of courses which aren\'t applied by you", "Курсы, на которые вы не записались"},
	      {"en.You are not allowed for this request", "Ваш статус не позволяет отправить запрос"},
	      {"en.Login or password contains are incorrect", "Неверное содержимое логина или пароля"},
	      {"en.Error", "Ошибка"},
	      {"en.Ascending", "По-возрастанию"},
	      {"en.Descending", "По-убыванию"},
	      {"en.AVG Mark", "Средняя оценка"},
	      {"en.Sort", "Сортировать"},
	      {"en.User not found", "Пользователь не найден"},
	      {"en.Start date is later than end", "Дата начала позже конечной"},
	   };
}
